name: ci
on:
    pull_request:
    push:
      branches:
        - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - run: sbt "; scalafmtCheckAll; scalafmtSbtCheck"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          cache: "sbt"
          distribution: "temurin"
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - run: sbt test
